global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'heroku_app'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['whatsup-8df2b91851a0.herokuapp.com']
