# prometheus.yml
global:
  scrape_interval: 30s  # Adjust scrape interval as needed

scrape_configs:
  - job_name: 'heroku_flask_app'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['whatsup-8df2b91851a0.herokuapp.com']
