scrape_configs:
  - job_name: 'metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['https://whatsup-8df2b91851a0.herokuapp.com/']
    basic_auth:
      username: 'admin'
      password: 'admin'
